apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-pipeline
spec:
  selector:
    matchLabels:
      app: ecommerce-pipeline
  replicas: 2
  template:
    metadata:
      labels:
        app: ecommerce-pipeline
    spec:
      containers:
        - name: ecommerce-pipeline
          image: mohumadkhald/ecommerce_ci_cd:1.0.0-16
          ports:
            - containerPort: 8080
