apiVersion: v1
kind: Service
metadata:
  name: ecommerce-pipeline-service
spec:
  selector:
    app: ecommerce-pipeline
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30001


