apiVersion: v1
kind: Service
metadata:
  name: ecommerce-pipeline-service
spec:
  selector:
    app: ecommerce-pipeline
  type: LoadBalancer
  ports:
    - port: 8443
      protocol: TCP
      targetPort: 8443
      nodePort: 30005

---
apiVersion: v1
kind: Service
metadata:
  name: some-mariadb-service
spec:
  selector:
    app: some-mariadb
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  clusterIP: None  # Headless service for direct pod access

---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  selector:
    app: phpmyadmin
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30002
  type: LoadBalancer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maria-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-env
data:
  DB_URL: jdbc:mariadb://some-mariadb-service:3306/ecommerce  # Use service name in the config map as well
  DB_NAME: ecommerce

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  MYSQL_USER: cm9vdA==  # base64 encoded value
  MYSQL_PASSWORD: cm9vdA==  # base64 encoded value
